"""universities and positions

Revision ID: 2ccf242e8b57
Revises:
Create Date: 2026-07-19 16:32:56.650530

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ccf242e8b57"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "universities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wikidata_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("website_url", sa.String(length=2048), nullable=False),
        sa.Column("listing_url", sa.String(length=2048), nullable=True),
        sa.Column("discovery_status", sa.String(length=16), nullable=False),
        sa.Column("extraction_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("schema_status", sa.String(length=16), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wikidata_id"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("university_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("deadline_raw", sa.String(length=256), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("indexed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["university_id"], ["universities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("positions")
    op.drop_table("universities")
    # ### end Alembic commands ###
