"""university sitelinks and last_scraped_at

Revision ID: 30e91c1adf78
Revises: e5d6bb18c252
Create Date: 2026-07-19 17:22:32.052836

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30e91c1adf78"
down_revision: str | None = "e5d6bb18c252"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("universities", sa.Column("sitelinks", sa.Integer(), nullable=False))
    op.add_column("universities", sa.Column("last_scraped_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("universities", "last_scraped_at")
    op.drop_column("universities", "sitelinks")
    # ### end Alembic commands ###
