"""listing pages

Revision ID: 5095eb3cc00e
Revises: 30e91c1adf78
Create Date: 2026-07-19 18:23:18.442818

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5095eb3cc00e"
down_revision: str | None = "30e91c1adf78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listing_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("university_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("extraction_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("schema_status", sa.String(length=16), nullable=False),
        sa.Column("pagination_param", sa.String(length=16), nullable=True),
        sa.Column("last_scraped_at", sa.DateTime(), nullable=True),
        sa.Column("discovered_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["university_id"], ["universities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.add_column("positions", sa.Column("listing_page_id", sa.Integer(), nullable=True))
    op.add_column("positions", sa.Column("institution_name", sa.String(length=512), nullable=True))
    op.add_column("positions", sa.Column("institution_country", sa.String(length=2), nullable=True))
    op.alter_column("positions", "university_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key(None, "positions", "listing_pages", ["listing_page_id"], ["id"], ondelete="SET NULL")
    op.execute(
        """
        INSERT INTO listing_pages (university_id, url, kind, source, extraction_schema, schema_status, last_scraped_at)
        SELECT id, listing_url, 'university', 'funnel', extraction_schema, schema_status, last_scraped_at
        FROM universities WHERE listing_url IS NOT NULL
        """
    )
    op.execute("UPDATE universities SET discovery_status='done' WHERE discovery_status='found'")
    op.drop_column("universities", "last_scraped_at")
    op.drop_column("universities", "listing_url")
    op.drop_column("universities", "schema_status")
    op.drop_column("universities", "extraction_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Irreversibile: la migrazione dati universities -> listing_pages non ha un inverso
    # affidabile (N pagine per ateneo non rientrano in una colonna singola).
    raise NotImplementedError("listing_pages migration is irreversible")
