"""position area and language

Revision ID: e5d6bb18c252
Revises: 2ccf242e8b57
Create Date: 2026-07-19 17:02:28.970199

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5d6bb18c252"
down_revision: str | None = "2ccf242e8b57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("positions", sa.Column("area", sa.String(length=256), nullable=True))
    op.add_column("positions", sa.Column("language", sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "language")
    op.drop_column("positions", "area")
    # ### end Alembic commands ###
